#!/bin/sh

alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"

# Colorize grep output 
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

# get top process eating memory
alias psmem='ps aux | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps aux | sort -nr -k 3 | head -5'

# .git
alias init='git init -b main'
alias gst='git status'
alias gadd='git add .'
alias gpull='git pull'
alias gpush='git push'
alias gdiff='git diff'
alias gb='git branch -a'
alias gco='git checkout'
alias gmain="git checkout main"
alias gcob='git checkout -b'
alias glog='git log'
alias gac='git add . && git commit -m'

# general
alias f='zi'
alias l='lsd -alh'
alias fzf='fzf -e --preview="cat {}"'
